#include <cstdint>
#include <cstdio>

// Include the hardware interface and the new NoC HAL.
#include "gemmini_rocc.h"
#include "noc_hal.h"

// Test Data (in Global Memory - GDDR6)
uint8_t global_inputs[64] = {
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
};
uint8_t global_weights[64] = {
    1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
    0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
    0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
    0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
};
uint8_t global_output[64] = { 0 };

// Main Test Function - Simulates the full TVM "Golden Path"
int main() {
    printf("Wrench Architect: Starting Full Pipeline Validation (W-4)...\n");

    // --- This test now simulates the entire "Golden Path" sequence ---
    // --- that will be generated by the TVM backend.                 ---

    // Golden Knowledge (TRM v2.0 Sec 6.0)
    #define WRENCH_L2_BASE 0x20000000
    uint64_t packed_dimensions = 0; // Placeholder for spec compliance.

    // 1. Define L2 pointers
    void* l2_inputs = (void*)WRENCH_L2_BASE;
    void* l2_weights = (void*)(WRENCH_L2_BASE + 64); // Simple offset for test
    void* l2_output = (void*)(WRENCH_L2_BASE + 128); // Simple offset for test

    // 2. Copy Inputs/Weights from Global (GDDR6) to Wrench L2
    printf("  [NOC] Copying inputs to Wrench L2...\n");
    noc_copy_blocking(l2_inputs, global_inputs, 64);
    printf("  [NOC] Copying weights to Wrench L2...\n");
    noc_copy_blocking(l2_weights, global_weights, 64);

    // 3. Call Wrench using L2 POINTERS (CONFIG FIRST)
    printf("  [WRENCH] Issuing hardware commands...\n");
    GEMMINI_CONFIG(packed_dimensions);
    GEMMINI_LOAD_A((uint64_t)l2_weights);
    GEMMINI_LOAD_B((uint64_t)l2_inputs);
    GEMMINI_FENCE(); // Load fence
    GEMMINI_EXECUTE((uint64_t)l2_output);
    GEMMINI_FENCE(); // Execute fence

    // 4. Copy Output from Wrench L2 back to Global (GDDR6)
    printf("  [NOC] Copying output back to Global Memory...\n");
    noc_copy_blocking(global_output, l2_output, 64);

    // 5. Validate Results in Global Memory
    printf("  [CPU] Validating results...\n");
    for (int i = 0; i < 64; ++i) {
        if (global_output[i] != global_inputs[i]) {
            printf("!!! VALIDATION FAIL: Mismatch at byte %d (Expected: %d, Got: %d)\n", i, global_inputs[i], global_output[i]);
            return -1;
        }
    }

    // Log Success
    printf("+++ VALIDATION PASS: Wrench Full Pipeline is 100%% correct.\n");
    return 0;
}
